builds:
- id: exoscale-csi-driver
  binary: exoscale-csi-driver
  main: ./cmd/exoscale-csi-driver
  env:
  - CGO_ENABLED=0
  - GO_PKG=github.com/exoscale/exoscale-csi-driver
  flags:
  - -mod=vendor
  - -trimpath
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
  goos:
  - linux
  goarch:
  - amd64

dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - "exoscale/csi-driver:latest"
  - "exoscale/csi-driver:{{ .Major }}"
  - "exoscale/csi-driver:{{ .Major }}.{{ .Minor }}"
  - "exoscale/csi-driver:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  dockerfile: Dockerfile
  build_flag_templates:
  - --pull
  - --build-arg="VERSION={{.Version}}"
  - --build-arg="VCS_REF={{.ShortCommit}}"
  - --build-arg="BUILD_DATE={{.Date}}"

signs:
- cmd: gpg
  args: ["--default-key", "7100E8BFD6199CE0374CB7F003686F8CDE378D41", "--detach-sign", "${artifact}"]
  artifacts: all

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

release:
  github:
    owner: exoscale
    name: exoscale-csi-driver
