apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invalid-pvc
  namespace: awesome
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200703Mi
  storageClassName: exoscale-sbs
