apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sbs-pvc
  namespace: awesome
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: exoscale-sbs
