apiVersion: v1
kind: ServiceAccount
metadata:
  name: exoscale-csi-node
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exoscale-csi-node-driver
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exoscale-csi-node-driver
subjects:
  - kind: ServiceAccount
    name: exoscale-csi-node
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: exoscale-csi-node-driver
  apiGroup: rbac.authorization.k8s.io
