name: DockerPush

# TODO this workflow is a temporary measure, remove it once CI release workflow is in place.

on:
  workflow_dispatch: # Let's us invoke the workflow manually
  push:
    branches:
    - 'main'

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: make go.mk
      - uses: ./go.mk/.github/actions/setup
      - name: Build Docker image
        run: make docker
      - name: Push Docker image
        run: make docker-push
